### ISSUE TITLE
Creating second MongoDB Template causes UnsupportedFeatureError

### ISSUE THREAD

**Issue by dmuecke** [spring-projects-experimental/.github#1]
In my application a primary MongoTemplate gets created using auto configuration. A second MongoTemplate gets created based on some business logic. Both databases are MongoDB Atlas clusters. During the creation of the second template I get an exception as shown below whereas the primary template works as expected.

Springboot: 2.4.5
spring-native: 0.9.2
Builder: paketobuildpacks/builder:tiny
Language: Kotlin
Java Version: 11

```

Exception in thread "cluster-ClusterId{value='60a4fa37759deb3f805b5b23', description='null'}-srv-rtds-prod-cluster-2-pl-0.ezl3n.mongodb.net" com.oracle.svm.core.jdk.UnsupportedFeatureError: JDK11OrLater: Target_java_lang_ClassLoader.trySetObjectField(String name, Object obj)
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
	at java.lang.ClassLoader.trySetObjectField(ClassLoader.java:315)
	at java.lang.ClassLoader.createOrGetClassLoaderValueMap(ClassLoader.java:2993)
	at java.lang.System$2.createOrGetClassLoaderValueMap(System.java:2126)
	at jdk.internal.loader.AbstractClassLoaderValue.map(AbstractClassLoaderValue.java:266)
	at jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:189)
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:711)
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at javax.naming.InitialContext.init(InitialContext.java:236)
	at javax.naming.InitialContext.<init>(InitialContext.java:208)
	at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
	at com.mongodb.internal.dns.DefaultDnsResolver.createDnsDirContext(DefaultDnsResolver.java:151)
	at com.mongodb.internal.dns.DefaultDnsResolver.resolveHostFromSrvRecords(DefaultDnsResolver.java:59)
	at com.mongodb.internal.connection.DefaultDnsSrvRecordMonitor$DnsSrvRecordMonitorRunnable.run(DefaultDnsSrvRecordMonitor.java:77)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)


```

**Comment by dmuecke** [comment]
Added to the wrong repo
